services:
  postgres:
    container_name: graphql2_course
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_student:/var/lib/postgresql/data
    networks:
      - postgres_student
    ports:
      - "5436:5432"
networks:
  postgres_student:
    driver: bridge
volumes:
  postgres_student: